name: Testing the Python code

on:
  push:
    branches:
      - main
jobs:
  build-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pycodestyle
        run: |
          pycodestyle src test
      - name: Test with pytest
        run: |
          PYTHONPATH=./:./src/ pytest test

